services:
  script:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    container_name: uvr-01
    tty: true
    environment:
      gpus: 'all'
      DISPLAY: :0
    command: 'python3 UVR.py'
    volumes:
      - ./volumes/inputs:/volumes/inputs
      - ./volumes/outpus:/volumes/outputs
      - ./volumes/models:/volumes/models
      - /tmp/.X11-unix:/tmp/.X11-unix
    logging:
      options:
        max-size: '200k'
        max-file: '10'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
